name: Linting

on:
    pull_request:
        branches: [main, dev]
    workflow_dispatch:

jobs:
    lint:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v3
              with:
                  fetch-depth: 0

            - name: Setup Environment
              uses: ./.github/actions/setup